version: '3'
services:
    app:
        build:
            context: ./
            args:
                WWWGROUP: '${WWWGROUP}'
        container_name: prod_app
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - './:/var/www'
        environment:
            WWWUSER: '${WWWUSER}'
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - prod
        depends_on:
            - mysql

    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: prod_mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './data/mysql:/var/lib/mysql'
            - '/etc/localtime:/etc/localtime:ro'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        networks:
            - prod
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
  prod:
    driver: bridge